"""Standardized API error codes for CertSentinel."""

INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
FILE_CORRUPTED = "FILE_CORRUPTED"
OCR_FAILED = "OCR_FAILED"
OCR_EMPTY_RESULT = "OCR_EMPTY_RESULT"
MODEL_INFERENCE_FAILED = "MODEL_INFERENCE_FAILED"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
VALIDATION_ERROR = "VALIDATION_ERROR"
PROCESSING_FAILED = "PROCESSING_FAILED"
PREPROCESSING_FAILED = "PREPROCESSING_FAILED"
DB_SAVE_FAILED = "DB_SAVE_FAILED"
RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
BATCH_LIMIT_EXCEEDED = "BATCH_LIMIT_EXCEEDED"
INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorCodes:
    INVALID_FILE_FORMAT = INVALID_FILE_FORMAT
    FILE_SIZE_EXCEEDED = FILE_SIZE_EXCEEDED
    FILE_CORRUPTED = FILE_CORRUPTED
    OCR_FAILED = OCR_FAILED
    OCR_EMPTY_RESULT = OCR_EMPTY_RESULT
    MODEL_INFERENCE_FAILED = MODEL_INFERENCE_FAILED
    RATE_LIMIT_EXCEEDED = RATE_LIMIT_EXCEEDED
    UNAUTHORIZED = UNAUTHORIZED
    FORBIDDEN = FORBIDDEN
    VALIDATION_ERROR = VALIDATION_ERROR
    PROCESSING_FAILED = PROCESSING_FAILED
    PREPROCESSING_FAILED = PREPROCESSING_FAILED
    DB_SAVE_FAILED = DB_SAVE_FAILED
    RECORD_NOT_FOUND = RECORD_NOT_FOUND
    BATCH_LIMIT_EXCEEDED = BATCH_LIMIT_EXCEEDED
    INTERNAL_ERROR = INTERNAL_ERROR

    # Backward-compatible aliases for older code paths.
    FILE_TOO_LARGE = FILE_SIZE_EXCEEDED
    INVALID_FILE_TYPE = INVALID_FILE_FORMAT
    MODEL_ERROR = MODEL_INFERENCE_FAILED
    DATABASE_ERROR = DB_SAVE_FAILED
